// Generated by gencpp from file testing_pkg/ResetEnvironment.msg
// DO NOT EDIT!


#ifndef TESTING_PKG_MESSAGE_RESETENVIRONMENT_H
#define TESTING_PKG_MESSAGE_RESETENVIRONMENT_H

#include <ros/service_traits.h>


#include <testing_pkg/ResetEnvironmentRequest.h>
#include <testing_pkg/ResetEnvironmentResponse.h>


namespace testing_pkg
{

struct ResetEnvironment
{

typedef ResetEnvironmentRequest Request;
typedef ResetEnvironmentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetEnvironment
} // namespace testing_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::testing_pkg::ResetEnvironment > {
  static const char* value()
  {
    return "4028ee4ec29cddea9b41f419b98a355d";
  }

  static const char* value(const ::testing_pkg::ResetEnvironment&) { return value(); }
};

template<>
struct DataType< ::testing_pkg::ResetEnvironment > {
  static const char* value()
  {
    return "testing_pkg/ResetEnvironment";
  }

  static const char* value(const ::testing_pkg::ResetEnvironment&) { return value(); }
};


// service_traits::MD5Sum< ::testing_pkg::ResetEnvironmentRequest> should match
// service_traits::MD5Sum< ::testing_pkg::ResetEnvironment >
template<>
struct MD5Sum< ::testing_pkg::ResetEnvironmentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::testing_pkg::ResetEnvironment >::value();
  }
  static const char* value(const ::testing_pkg::ResetEnvironmentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::testing_pkg::ResetEnvironmentRequest> should match
// service_traits::DataType< ::testing_pkg::ResetEnvironment >
template<>
struct DataType< ::testing_pkg::ResetEnvironmentRequest>
{
  static const char* value()
  {
    return DataType< ::testing_pkg::ResetEnvironment >::value();
  }
  static const char* value(const ::testing_pkg::ResetEnvironmentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::testing_pkg::ResetEnvironmentResponse> should match
// service_traits::MD5Sum< ::testing_pkg::ResetEnvironment >
template<>
struct MD5Sum< ::testing_pkg::ResetEnvironmentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::testing_pkg::ResetEnvironment >::value();
  }
  static const char* value(const ::testing_pkg::ResetEnvironmentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::testing_pkg::ResetEnvironmentResponse> should match
// service_traits::DataType< ::testing_pkg::ResetEnvironment >
template<>
struct DataType< ::testing_pkg::ResetEnvironmentResponse>
{
  static const char* value()
  {
    return DataType< ::testing_pkg::ResetEnvironment >::value();
  }
  static const char* value(const ::testing_pkg::ResetEnvironmentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TESTING_PKG_MESSAGE_RESETENVIRONMENT_H
